[package]
name = "mun_test"
version = "0.1.0"
authors = ["jacob"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mun_runtime = "0.2"
rand = "0.7"
